### ISSUE TITLE
Keystore password was incorrect

### ISSUE THREAD

**Issue by sannidhi** [bendalby82/cf-tcp-routing-ssl#4]
Hi Ben,

I followed the instructions for creating the same tcp-routing app - created the resources folder under src/main and created the application properties you mentioned with the password for the keystore. Changed the password when I ran the  keytool -genkey command. However, I am seeing the following in the cf logs when I try to `mvn clean package` followed by `cf push`: 
```Caused by: java.io.IOException: keystore password was incorrect```

Do you have any idea what I could be missing? I also searched the project for "CHANGEME" occurrences but was unable to find any.  Or is there any documentation/step I am missing before pushing successfully? 

Thanks for your help!

**Comment by sannidhi** [comment]
It worked alright after a clean package, probably had a leftover old password somewhere. Thanks!

**Comment by bendalby82** [comment]
Thanks for letting me know, Sannidhi - you beat me to it!
